modid=nativeaccelerator
name=Native Accelerator
version=${project.version}
mainclass=com.asbestosstar.nativeaccelerator.featurecreep.NativeAcceleratorFeatureCreep
spongemixinconfig=nativeaccelerator.mixins.json
